create schema sublanguages;

-- this is a line comment

-- ctr + /

/*
 * this is a block comment
 * ctr + shift + /  
 * */

/*
 * What is SQL?
 * 		- Structured Query Language
 * 		- it is a language designed for manipulating relational databases
 * 
 * What is a DBMS?
 * 	Database Management System
 * 	- We are using Microsoft SQL Server
 * 	- the flavor of SQL we are using is called tsql
 * 
 * 
 * There are 5 sublanguages of SQL: (POPULAR QC QUESTION)
 * 	- DDL
 * 		- Data Definition Language
 * 		- deals with manipulating the table structures
 * 		- keywords: create, alter, drop, truncate
 * 	- DML
 * 		- Data Manipulation Language
 * 		- deals with manipulating the records within the table
 * 		- keywords: insert, update, delete
 * 	- DQL
 * 		- Data Query Language
 * 		- deals with retrieving information from the database
 * 		- keywords: select
 * 	- DCL
 * 		- Data Control Language
 * 		- deals with granting and revoking access to database and schemas
 * 		- keywords: grant, revoke
 * 	- TCL
 * 		- Transaction Control Language
 * 		- deals with making official commits to the database
 * 		- commit, rollback, savepoint
 * 
 * 
 * What is a transaction?
 * 	- its an official commit to the database
 * 
 * What are the properties of a transaction (ACID)? (POPULAR QC QUESTION)
 * 	- Atomicity: All or nothing... all operations will execute successfully or none at all
 * 	- Consistency: all constraints are enforced
 * 	- Isolation: Transactions cannot interefere with one another 
 * 	- Durability: once a commit happens, that is the new state of the database
 * */



/*
 * DDL
 * 	
 * What are the datatypes of sql?
 * 	- varchar(50): utilize for strings
 * 	- double precision: used for decimals
 * 	- date: provide a date value to the column
 *  - int: utilized for whole numbers
 * 	- bit: 1 or a 0... utilized for true or false values
 * 
 * What is a constraint?
 * 	- rules a column must follow
 * 
 * What are some constraints we can use?
 * 	- unique: the value needs to be unique within the column
 * 	- not null: you must have a value for that specific column
 * 	- default: if a value is not inserted, we can define a default value to be inputted
 * 
 * 
 * What is a primary key?
 * 		- its a unique identifier for a record in a table
 * 
 * There are 3 different types of primary keys:
 * 		- natural key: unique identifier that is generated outside of the database
 * 			- examples: username, ssn, phone number, email
 * 		- surrogate keys: autogenerated from inside of the database
 * 			- there is a constraint called identity
 * 		- composite keys:
 * 			- unique identifier from the combination of 2 or more columns
 * */

 create table sublanguages.users(
 	username varchar(50) unique not null,
 	password varchar(50) not null,
 	age int, -- since i didnt add a constraint, this value can be null
 	net_worth double precision not null,
 	date_created date default getdate(),
 	primary key (username)
 );

alter table sublanguages.users drop constraint DF__users__likes_cil__4E53A1AA;

alter table sublanguages.users drop column likes_cilantro;


-- we utilize the drop keyword to remove a table
drop table sublanguages.users;



/*
 * DML - Data Manipulation Language
 * 	deals with manipulating the records in a table
 * */

insert into sublanguages.users (username, password, net_worth) values ('jane123','pass123', 1000000000.45);

update sublanguages.users set age = 45, password = 'pass123' where username = 'steve321';

delete from sublanguages.users where net_worth > 100;

select * from sublanguages.users;



create table sublanguages.posts(
	post_id int identity, --identity auto increments the values in a column...used for surrogate keys
	content varchar(255) not null,
	user_fk varchar(50) foreign key references sublanguages.users(username),
	primary key(post_id)
);

insert into sublanguages.posts (content, user_fk) values ('Janes second post', 'jane123');

SELECT * from sublanguages.posts;


drop table sublanguages.posts;

/*
 * What is multiplicity?
 * 	- the relationship between two tables
 * 
 * 	- one to one
 * 	- one to many
 * 		- the "many" table has a foreign key to the primary key of the "one" table
 * 	- many to one
 * 		- the "many" table has a foreign key to the primary key of the "one" table
 * 	- many to many
 * 		- you need to create an external table called a junction table
 * 
 * user posts
 * 
 * 
 * What is a foreign key?
 * 	- a column that references another column
 * 	- we utilize them to relate tables to eachother
 * 
 * */

create table sublanguages.likes(
	post_fk int foreign key references sublanguages.posts(post_id),
	user_fk varchar(50) foreign key references sublanguages.users(username),
	primary key (post_fk, user_fk)
);


select * from sublanguages.users;

select * from sublanguages.posts;

select * from sublanguages.likes;

insert into sublanguages.likes (post_fk, user_fk) values (1, 'jane123');









