name: CI

# When to run this particular pipeline
on:
# runs on pushes to "main" and "staging" branch
  push:
    branches: [ "main", "staging"]
# runs whenever pr has been raised to main or staging branch
  pull_request:
    branches: [ "main", "staging"]
# allows me to manually trigger this pipeline
  workflow_dispatch:

# Just a way to bundle a certain commands together into a unit
jobs:
# a job's name
  build:

    # Which VM/environment should these commands run
    runs-on: windows-latest

    # what to do in this job("build")
    steps:
    # get java 11 (for sonar cloud)
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    # First checkout our repository (aka get our code)
    - uses: actions/checkout@v3
    
    # Get .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    # Restore our dependencies
    - name: Restore dependencies
      run: dotnet restore 06DevOps/PokemonStorageSystem/PokeStorageSystem.sln
    
    # Make sure all tests pass
    - name: Test
      run: dotnet test 06DevOps/PokemonStorageSystem/Tests --verbosity normal
    
    # Try building the app
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"220620NET_trainer-code" /o:"220620net" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        dotnet build --no-restore 06DevOps/PokemonStorageSystem/PokeStorageSystem.sln
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
